sudo: required
language: python
services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t nctiggy/teams-notification-resource .
script:
  - docker push nctiggy/teams-notification-resource
